# Generated by Django 5.0.6 on 2024-06-07 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0003_alter_downloadedsong_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='downloadedsong',
            table=None,
        ),
    ]
