# Generated by Django 5.0.6 on 2024-06-07 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_info', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Songwriter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('artists', models.ManyToManyField(related_name='albums', to='royalty_management.artist')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='royalty_management.label')),
            ],
        ),
        migrations.CreateModel(
            name='Royalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_royalty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('artists', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='royalty_management.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('duration', models.IntegerField(help_text='Duration in seconds')),
                ('total_plays', models.IntegerField(default=0)),
                ('total_downloads', models.IntegerField(default=0)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='royalty_management.album')),
                ('artists', models.ManyToManyField(related_name='songs', to='royalty_management.artist')),
                ('songwriters', models.ManyToManyField(related_name='songs', to='royalty_management.songwriter')),
            ],
        ),
    ]
